/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/designs": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Designs */
    get: operations["list_designs_api_designs_get"];
    put?: never;
    /** Upload Design */
    post: operations["upload_design_api_designs_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/garment-profiles": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Garment Profiles */
    get: operations["list_garment_profiles_api_garment_profiles_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Health */
    get: operations["health_api_health_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/listing-designs": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Listing Designs */
    get: operations["list_listing_designs_api_listing_designs_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/listing-designs/{name}/thumbnail": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Listing Design Thumbnail
     * @description The artwork itself, downscaled -- what the listings table, its hover
     *     card and the editor's design strip all show.
     *
     *     Distinct from ``designs.py``'s calibrator library for the same reason
     *     ``GET /api/listing-designs`` is: ``designs/`` holds artwork that ships,
     *     ``test-designs/`` holds calibration targets, and a listing's design is
     *     never one of the latter.
     *
     *     An unusable *name* needs nothing here: ``InvalidNameError`` out of
     *     ``design_file`` becomes a 400 through the app-wide handler in ``app.py``.
     */
    get: operations["listing_design_thumbnail_api_listing_designs__name__thumbnail_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/listings": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Listings */
    get: operations["list_listings_api_listings_get"];
    put?: never;
    /** Create Listing */
    post: operations["create_listing_api_listings_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/listings/{name}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Listing */
    get: operations["get_listing_api_listings__name__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Patch Listing */
    patch: operations["patch_listing_api_listings__name__patch"];
    trace?: never;
  };
  "/api/pricing-plans": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Pricing Plans */
    get: operations["list_pricing_plans_api_pricing_plans_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/templates": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Templates */
    get: operations["list_templates_api_templates_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/templates/{name}/colour-report": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Colour Report
     * @description What each photo will be taken as if this becomes a colour-matrix set.
     *
     *     Shown in the kind picker before committing, so a badly named file is seen
     *     while it is still cheap to think about. A row with ``clean: false`` is one
     *     ``assign_kind`` will rename on disk (PRD 7a: the filename *is* the
     *     slugified colour, and a directory whose filenames disagree with the
     *     colours they mean is the state that rule exists to prevent).
     */
    get: operations["colour_report_api_templates__name__colour_report_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/templates/{name}/config": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Config */
    get: operations["get_config_api_templates__name__config_get"];
    /** Put Config */
    put: operations["put_config_api_templates__name__config_put"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/templates/{name}/kind": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Assign Kind
     * @description The first calibration step: say what this template is, and get the
     *     starting ``template.yaml`` for that shape.
     *
     *     Refuses a template that already has a config. Kind decides the whole file
     *     shape (A11), so changing it would discard whatever calibration was done in
     *     the old shape's fields -- and doing that silently, from a picker, is the
     *     kind of data loss nobody would think to look for.
     */
    post: operations["assign_kind_api_templates__name__kind_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/templates/{name}/preview": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Preview */
    post: operations["preview_api_templates__name__preview_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/templates/{name}/thumbnail": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Thumbnail
     * @description The template's own photo, downscaled, for the rail.
     *
     *     Not a render: the rail shows every template in the workspace at once, and
     *     running the real pipeline once per row would make opening the calibrator
     *     cost as much as calibrating. Which photo is shown is
     *     :meth:`~etsy_listings.workspace.workspace.Workspace.template_preview_photo`'s
     *     question, not this endpoint's.
     *
     *     ``colour`` narrows that to one photo of a ``colour-matrix`` set, for
     *     callers that are showing a *particular* variant rather than standing in
     *     for the template: the listings editor's reel draws one tile per
     *     ``media`` entry, and without this every colour of a set drew the same
     *     picture, since ``template_preview_photo`` deliberately answers "any one
     *     of them". Resolution goes through
     *     :meth:`~etsy_listings.workspace.workspace.Workspace.template_base_image`,
     *     which owns PRD 7a's filename convention and its trailing-segment
     *     fallback -- this endpoint must not glob for ``{colour}.png`` itself.
     *
     *     How it is downscaled and served is :mod:`etsy_listings.ui.api.thumbnails`'
     *     question -- the listings table asks the same one of a design.
     */
    get: operations["thumbnail_api_templates__name__thumbnail_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/workspace": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Workspace */
    get: operations["get_workspace_api_workspace_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/{full_path}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Spa Fallback */
    get: operations["spa_fallback__full_path__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** AssignKindRequest */
    AssignKindRequest: {
      /**
       * Kind
       * @enum {string}
       */
      kind: "colour-matrix" | "multiple" | "single";
    };
    /** Body_upload_design_api_designs_post */
    Body_upload_design_api_designs_post: {
      /** File */
      file: string;
    };
    /**
     * ColourMatrixPreviewRequest
     * @description Disambiguated from the other two preview shapes by required fields
     *     alone (``colour`` here, ``placements`` on ``MultiplePreviewRequest``,
     *     neither on ``SinglePreviewRequest``) -- extra fields are ignored rather
     *     than forbidden, since a natural client pattern is spreading a whole
     *     ``GET .../config`` response (which includes ``kind``) into the body.
     */
    ColourMatrixPreviewRequest: {
      /** Bounding Box */
      bounding_box: [
        components["schemas"]["Point"],
        components["schemas"]["Point"],
        components["schemas"]["Point"],
        components["schemas"]["Point"],
      ];
      /** Colour */
      colour: string;
      /**
       * Design
       * @default bundled-grid
       */
      design: string;
      /**
       * @default {
       *       "enabled": false,
       *       "strength": 0
       *     }
       */
      displace: components["schemas"]["DisplaceConfig"];
      /**
       * @default {
       *       "blend": "soft-light",
       *       "enabled": true,
       *       "opacity": 0.6
       *     }
       */
      shade: components["schemas"]["ShadeConfig"];
    };
    /**
     * ColourMatrixTemplate
     * @description One photo per colour, same design position in all of them. Scene
     *     images are ``{colour-slug}.png`` per colour (PRD 7a) -- there is no
     *     ``colours:`` list in the YAML, since the filenames present in the
     *     directory *are* the colour set.
     */
    ColourMatrixTemplate: {
      /** Bounding Box */
      bounding_box: [
        components["schemas"]["Point"],
        components["schemas"]["Point"],
        components["schemas"]["Point"],
        components["schemas"]["Point"],
      ];
      /**
       * @default {
       *       "enabled": false,
       *       "strength": 0
       *     }
       */
      displace: components["schemas"]["DisplaceConfig"];
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      kind: "colour-matrix";
      /**
       * @default {
       *       "blend": "soft-light",
       *       "enabled": true,
       *       "opacity": 0.6
       *     }
       */
      shade: components["schemas"]["ShadeConfig"];
    };
    /**
     * ColourReportRow
     * @description What one photo in a candidate ``colour-matrix`` set will be taken as.
     *
     *     Reporting only: PRD 7a makes the filename the source of truth, so there is
     *     no manual mapping to offer and nothing here changes a name.
     */
    ColourReportRow: {
      /** Clean */
      clean: boolean;
      /** Colour */
      colour: string;
      /** Filename */
      filename: string;
    };
    /** CreateListingRequest */
    CreateListingRequest: {
      /** Colors */
      colors: string[];
      /** Design */
      design: string;
      /** Garment Profile */
      garment_profile: string;
      /** Name */
      name: string;
    };
    /**
     * DesignSummary
     * @description One entry in the calibrator's test-design library (A19).
     *
     *     ``bundled-grid``: the grid/ruler target, for spotting warp/displacement
     *     errors. ``bundled-on-light``/``bundled-on-dark``: deterministic
     *     ink-coloured targets, so a mis-resolved artwork is visually obvious in the
     *     calibrator, not just described in a diff. ``upload``: a PNG the user added,
     *     for judging a real ink weight on a real garment -- the question the grid
     *     cannot answer.
     */
    DesignSummary: {
      /** Id */
      id: string;
      /** Label */
      label: string;
      /**
       * Source
       * @enum {string}
       */
      source: "bundled" | "upload";
    };
    /**
     * DisplaceConfig
     * @description PRD: implemented but off by default -- over-strong displacement looks
     *     melted, so it's tuned per template in the calibrator's live preview.
     */
    DisplaceConfig: {
      /**
       * Enabled
       * @default false
       */
      enabled: boolean;
      /**
       * Strength
       * @default 0
       */
      strength: number;
    };
    /** EtsyListingConfig */
    EtsyListingConfig: {
      /**
       * Description
       * @default <generate>
       */
      description: string;
      /**
       * Materials
       * @default []
       */
      materials: string[];
      /** Renewal */
      renewal?: ("manual" | "auto") | null;
      /** Section */
      section?: string | null;
      /** Shipping Profile */
      shipping_profile?: string | null;
      /**
       * Tags
       * @default <generate>
       */
      tags: string[] | "<generate>";
      /**
       * Title
       * @default <generate>
       */
      title: string;
      /** Variation Images */
      variation_images?: string | null;
    };
    /** GarmentProfileSummary */
    GarmentProfileSummary: {
      /** Colors */
      colors: {
        [key: string]: "light" | "dark";
      };
      /** Name */
      name: string;
      /** Sizes */
      sizes: string[];
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** Issue */
    Issue: {
      /** Message */
      message: string;
      /**
       * Severity
       * @enum {string}
       */
      severity: "block" | "warn";
      /**
       * Tab
       * @enum {string}
       */
      tab: "variants" | "images" | "details";
      /** Where */
      where: string;
    };
    /** IssueCounts */
    IssueCounts: {
      /** Block */
      block: number;
      /** Warn */
      warn: number;
    };
    /** ListingDesignSummary */
    ListingDesignSummary: {
      /** File */
      file: string;
      /** Name */
      name: string;
    };
    /**
     * ListingDetail
     * @description The full `Listing`, plus what the editor needs and nothing a listing
     *     itself would ever store: computed status, computed issues, and (only
     *     meaningful right after a PATCH) which fields a rejected candidate failed
     *     on.
     */
    ListingDetail: {
      /**
       * Artwork
       * @default {}
       */
      artwork: {
        [key: string]: string;
      };
      /** Brief */
      brief: string;
      /** Colors */
      colors: string[];
      /** Design */
      design: {
        [key: string]: string;
      };
      /**
       * @default {
       *       "description": "<generate>",
       *       "materials": [],
       *       "tags": "<generate>",
       *       "title": "<generate>"
       *     }
       */
      etsy: components["schemas"]["EtsyListingConfig"];
      /** Etsy Listing Id */
      etsy_listing_id?: number | null;
      /**
       * Field Errors
       * @default {}
       */
      field_errors: {
        [key: string]: string;
      };
      /** Garment Profile */
      garment_profile: string;
      /** Issues */
      issues: components["schemas"]["Issue"][];
      /** Media */
      media: (components["schemas"]["TemplateMediaEntry"] | string)[];
      /** Name */
      name: string;
      /**
       * Price Overrides
       * @default {}
       */
      price_overrides: {
        [key: string]: {
          [key: string]: string;
        };
      };
      /**
       * Prices
       * @default {}
       */
      prices: {
        [key: string]: string;
      };
      /** Pricing Plan */
      pricing_plan?: string | null;
      /** Pricing Plan Name */
      pricing_plan_name?: string | null;
      /** Printify Product Id */
      printify_product_id?: string | null;
      /**
       * Resolved Prices
       * @default []
       */
      resolved_prices: components["schemas"]["ResolvedPrice"][];
      /**
       * Status
       * @enum {string}
       */
      status: "draft" | "published";
    };
    /** ListingSummary */
    ListingSummary: {
      /** Colour Count */
      colour_count: number;
      /** Design */
      design: string | null;
      /** Etsy Listing Id */
      etsy_listing_id?: number | null;
      /** Garment Profile */
      garment_profile: string;
      issue_counts: components["schemas"]["IssueCounts"];
      /** Name */
      name: string;
      /** Printify Product Id */
      printify_product_id?: string | null;
      /**
       * Status
       * @enum {string}
       */
      status: "draft" | "published";
    };
    /** MultiplePreviewRequest */
    MultiplePreviewRequest: {
      /**
       * Design
       * @default bundled-grid
       */
      design: string;
      /**
       * @default {
       *       "enabled": false,
       *       "strength": 0
       *     }
       */
      displace: components["schemas"]["DisplaceConfig"];
      /** Placements */
      placements: components["schemas"]["Placement"][];
      /**
       * @default {
       *       "blend": "soft-light",
       *       "enabled": true,
       *       "opacity": 0.6
       *     }
       */
      shade: components["schemas"]["ShadeConfig"];
    };
    /**
     * MultipleTemplate
     * @description Several garments in one photo. ``displace``/``shade`` are scene-level
     *     only -- one photo, one lighting pass; a placement needing different
     *     rendering treatment belongs in its own template instead.
     */
    MultipleTemplate: {
      /**
       * Colour Coverage
       * @default exact
       * @enum {string}
       */
      colour_coverage: "exact" | "subset";
      /**
       * @default {
       *       "enabled": false,
       *       "strength": 0
       *     }
       */
      displace: components["schemas"]["DisplaceConfig"];
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      kind: "multiple";
      /** Placements */
      placements: components["schemas"]["Placement"][];
      /**
       * @default {
       *       "blend": "soft-light",
       *       "enabled": true,
       *       "opacity": 0.6
       *     }
       */
      shade: components["schemas"]["ShadeConfig"];
    };
    /**
     * Placement
     * @description One garment within a ``multiple``-kind scene.
     */
    Placement: {
      /** Artwork */
      artwork?: string | null;
      /** Bounding Box */
      bounding_box: [
        components["schemas"]["Point"],
        components["schemas"]["Point"],
        components["schemas"]["Point"],
        components["schemas"]["Point"],
      ];
      /** Colour */
      colour: string;
    };
    /** Point */
    Point: {
      /** X */
      x: number;
      /** Y */
      y: number;
    };
    /** PricingPlanSummary */
    PricingPlanSummary: {
      /** Compatible */
      compatible: boolean;
      /** Garment Profile */
      garment_profile: string;
      /** Name */
      name: string;
    };
    /** ResolvedPrice */
    ResolvedPrice: {
      /** Amount */
      amount: string;
      /** Size */
      size: string;
    };
    /**
     * ShadeConfig
     * @description Blends the base mockup photo's own greyscale lighting over the printed
     *     design, so a flat design picks up the garment's real fold shadows and
     *     light falloff instead of looking pasted on as a flat rectangle -- this is
     *     why a plain flat-lay PNG is enough to mock up, with no purchased
     *     Photoshop lighting map needed. On by default: almost every mockup needs
     *     it. ``multiply`` crushes prints on dark garments, so ``soft-light`` or a
     *     mid-grey pivot is used for those instead.
     */
    ShadeConfig: {
      /**
       * Blend
       * @default soft-light
       * @enum {string}
       */
      blend: "multiply" | "soft-light" | "grey-pivot";
      /**
       * Enabled
       * @default true
       */
      enabled: boolean;
      /**
       * Opacity
       * @default 0.6
       */
      opacity: number;
    };
    /** SinglePreviewRequest */
    SinglePreviewRequest: {
      /** Bounding Box */
      bounding_box: [
        components["schemas"]["Point"],
        components["schemas"]["Point"],
        components["schemas"]["Point"],
        components["schemas"]["Point"],
      ];
      /**
       * Design
       * @default bundled-grid
       */
      design: string;
      /**
       * @default {
       *       "enabled": false,
       *       "strength": 0
       *     }
       */
      displace: components["schemas"]["DisplaceConfig"];
      /**
       * @default {
       *       "blend": "soft-light",
       *       "enabled": true,
       *       "opacity": 0.6
       *     }
       */
      shade: components["schemas"]["ShadeConfig"];
    };
    /**
     * SingleTemplate
     * @description One photo, one garment -- a lifestyle shot, a folded product photo,
     *     anything that isn't part of a colour set.
     */
    SingleTemplate: {
      /** Artwork */
      artwork?: string | null;
      /** Bounding Box */
      bounding_box: [
        components["schemas"]["Point"],
        components["schemas"]["Point"],
        components["schemas"]["Point"],
        components["schemas"]["Point"],
      ];
      /** Colour */
      colour?: string | null;
      /**
       * @default {
       *       "enabled": false,
       *       "strength": 0
       *     }
       */
      displace: components["schemas"]["DisplaceConfig"];
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      kind: "single";
      /**
       * @default {
       *       "blend": "soft-light",
       *       "enabled": true,
       *       "opacity": 0.6
       *     }
       */
      shade: components["schemas"]["ShadeConfig"];
    };
    /**
     * TemplateMediaEntry
     * @description Always-explicit template reference -- there is no bare-colour
     *     shorthand. ``colour`` is required when the referenced template is
     *     ``colour-matrix`` kind (which colour's photo) and must be omitted for
     *     ``multiple``/``single`` kind (exactly one output each, nothing to
     *     disambiguate).
     */
    TemplateMediaEntry: {
      /** Colour */
      colour?: string | null;
      /** Template */
      template: string;
    };
    /** TemplateSummary */
    TemplateSummary: {
      /** Colours */
      colours: string[];
      /** Has Config */
      has_config: boolean;
      /** Height */
      height?: number | null;
      /** Kind */
      kind: ("colour-matrix" | "multiple" | "single") | null;
      /** Name */
      name: string;
      /**
       * Status
       * @enum {string}
       */
      status: "needs-calibration" | "calibrated";
      /** Status Reason */
      status_reason?: string | null;
      /** Width */
      width?: number | null;
    };
    /** ValidationError */
    ValidationError: {
      /** Context */
      ctx?: Record<string, never>;
      /** Input */
      input?: unknown;
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
    /**
     * WorkspaceSummary
     * @description Which workspace the UI is pointed at. One workspace is one shop, so the
     *     sidebar names it -- the difference between a test shop and the real one is
     *     worth seeing before an edit, not after an apply.
     */
    WorkspaceSummary: {
      /** Shop Name */
      shop_name: string | null;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  list_designs_api_designs_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DesignSummary"][];
        };
      };
    };
  };
  upload_design_api_designs_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "multipart/form-data": components["schemas"]["Body_upload_design_api_designs_post"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DesignSummary"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_garment_profiles_api_garment_profiles_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GarmentProfileSummary"][];
        };
      };
    };
  };
  health_api_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: string;
          };
        };
      };
    };
  };
  list_listing_designs_api_listing_designs_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ListingDesignSummary"][];
        };
      };
    };
  };
  listing_design_thumbnail_api_listing_designs__name__thumbnail_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        name: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_listings_api_listings_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ListingSummary"][];
        };
      };
    };
  };
  create_listing_api_listings_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateListingRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ListingDetail"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_listing_api_listings__name__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        name: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ListingDetail"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  patch_listing_api_listings__name__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        name: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          [key: string]: unknown;
        };
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ListingDetail"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_pricing_plans_api_pricing_plans_get: {
    parameters: {
      query: {
        garment_profile: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PricingPlanSummary"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_templates_api_templates_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TemplateSummary"][];
        };
      };
    };
  };
  colour_report_api_templates__name__colour_report_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        name: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ColourReportRow"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_config_api_templates__name__config_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        name: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json":
            | components["schemas"]["ColourMatrixTemplate"]
            | components["schemas"]["MultipleTemplate"]
            | components["schemas"]["SingleTemplate"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  put_config_api_templates__name__config_put: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        name: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json":
          | components["schemas"]["ColourMatrixTemplate"]
          | components["schemas"]["MultipleTemplate"]
          | components["schemas"]["SingleTemplate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json":
            | components["schemas"]["ColourMatrixTemplate"]
            | components["schemas"]["MultipleTemplate"]
            | components["schemas"]["SingleTemplate"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  assign_kind_api_templates__name__kind_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        name: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AssignKindRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json":
            | components["schemas"]["ColourMatrixTemplate"]
            | components["schemas"]["MultipleTemplate"]
            | components["schemas"]["SingleTemplate"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  preview_api_templates__name__preview_post: {
    parameters: {
      query?: {
        scale?: "editor" | "full";
      };
      header?: never;
      path: {
        name: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json":
          | components["schemas"]["ColourMatrixPreviewRequest"]
          | components["schemas"]["MultiplePreviewRequest"]
          | components["schemas"]["SinglePreviewRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  thumbnail_api_templates__name__thumbnail_get: {
    parameters: {
      query?: {
        colour?: string | null;
      };
      header?: never;
      path: {
        name: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_workspace_api_workspace_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["WorkspaceSummary"];
        };
      };
    };
  };
  spa_fallback__full_path__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        full_path: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
}
