/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Health */
    get: operations["health_api_health_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/templates": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Templates */
    get: operations["list_templates_api_templates_get"];
    put?: never;
    /** Upload Template */
    post: operations["upload_template_api_templates_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/templates/{name}/config": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Config */
    get: operations["get_config_api_templates__name__config_get"];
    /** Put Config */
    put: operations["put_config_api_templates__name__config_put"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/templates/{name}/preview": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Preview */
    post: operations["preview_api_templates__name__preview_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/{full_path}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Spa Fallback */
    get: operations["spa_fallback__full_path__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** Body_upload_template_api_templates_post */
    Body_upload_template_api_templates_post: {
      /** Files */
      files: string[];
    };
    /**
     * DisplaceConfig
     * @description PRD: implemented but off by default -- over-strong displacement looks
     *     melted, so it's tuned per template in the calibrator's live preview.
     */
    DisplaceConfig: {
      /**
       * Enabled
       * @default false
       */
      enabled: boolean;
      /**
       * Strength
       * @default 0
       */
      strength: number;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** PreviewRequest */
    PreviewRequest: {
      /** Colour */
      colour: string;
      /**
       * Design
       * @default bundled-grid
       * @constant
       */
      design: "bundled-grid";
      /**
       * @default {
       *       "enabled": false,
       *       "strength": 0
       *     }
       */
      displace: components["schemas"]["DisplaceConfig"];
      /**
       * @default {
       *       "blend": "soft-light",
       *       "enabled": true,
       *       "opacity": 0.6
       *     }
       */
      shade: components["schemas"]["ShadeConfig"];
      warp: components["schemas"]["WarpConfig"];
    };
    /**
     * ShadeConfig
     * @description PRD: on by default. ``multiply`` crushes prints on dark garments, so
     *     ``soft-light`` or a mid-grey pivot is used for those instead.
     */
    ShadeConfig: {
      /**
       * Blend
       * @default soft-light
       * @enum {string}
       */
      blend: "multiply" | "soft-light" | "grey-pivot";
      /**
       * Enabled
       * @default true
       */
      enabled: boolean;
      /**
       * Opacity
       * @default 0.6
       */
      opacity: number;
    };
    /** TemplateConfigResponse */
    TemplateConfigResponse: {
      displace: components["schemas"]["DisplaceConfig"];
      shade: components["schemas"]["ShadeConfig"];
      warp: components["schemas"]["WarpConfig"];
    };
    /** TemplateConfigUpdate */
    TemplateConfigUpdate: {
      /**
       * @default {
       *       "enabled": false,
       *       "strength": 0
       *     }
       */
      displace: components["schemas"]["DisplaceConfig"];
      /**
       * @default {
       *       "blend": "soft-light",
       *       "enabled": true,
       *       "opacity": 0.6
       *     }
       */
      shade: components["schemas"]["ShadeConfig"];
      warp: components["schemas"]["WarpConfig"];
    };
    /** TemplateSummary */
    TemplateSummary: {
      /** Colours */
      colours: string[];
      /** Has Config */
      has_config: boolean;
      /** Name */
      name: string;
    };
    /** UploadResponse */
    UploadResponse: {
      /** Colours */
      colours: string[];
      /** Name */
      name: string;
    };
    /** ValidationError */
    ValidationError: {
      /** Context */
      ctx?: Record<string, never>;
      /** Input */
      input?: unknown;
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
    /** WarpConfig */
    WarpConfig: {
      /** Quad */
      quad: [[number, number], [number, number], [number, number], [number, number]];
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  health_api_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: string;
          };
        };
      };
    };
  };
  list_templates_api_templates_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TemplateSummary"][];
        };
      };
    };
  };
  upload_template_api_templates_post: {
    parameters: {
      query: {
        name: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "multipart/form-data": components["schemas"]["Body_upload_template_api_templates_post"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UploadResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_config_api_templates__name__config_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        name: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TemplateConfigResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  put_config_api_templates__name__config_put: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        name: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["TemplateConfigUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TemplateConfigResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  preview_api_templates__name__preview_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        name: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PreviewRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  spa_fallback__full_path__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        full_path: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
}
