/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/common-media": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Common Media
     * @description The shared assets a listing can add to `media:` as a bare path.
     *
     *     Distinct from both design endpoints: ``designs/`` is the artwork that gets
     *     printed, ``test-designs/`` is calibration targets, and these are finished
     *     pictures (a sizing chart, care instructions) uploaded to Etsy as-is,
     *     never rendered onto a garment.
     */
    get: operations["list_common_media_api_common_media_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/common-media/{name}/file": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Common Media File
     * @description The shared asset at its own size, for the editor's preview pane and its
     *     lightbox -- the two places a picture is *judged* rather than picked out of
     *     a list.
     *
     *     The bytes as they sit on disk, not a re-encode: a mockup template's
     *     counterpart (`GET .../design-preview`) has to run the real pipeline to
     *     exist at all, but this file is already exactly what would be uploaded to
     *     Etsy, and the one thing worth seeing full-size is what Etsy will get.
     */
    get: operations["common_media_file_api_common_media__name__file_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/common-media/{name}/thumbnail": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Common Media Thumbnail
     * @description An unusable *name* needs nothing here: ``InvalidNameError`` out of
     *     ``common_media_file`` becomes a 400 through the app-wide handler.
     */
    get: operations["common_media_thumbnail_api_common_media__name__thumbnail_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/designs": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Designs */
    get: operations["list_designs_api_designs_get"];
    put?: never;
    /** Upload Design */
    post: operations["upload_design_api_designs_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/etsy/sections": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Etsy Sections
     * @description The live shop's sections, for the Details tab's Section dropdown.
     *     Empty (not a 500) for a workspace with no `shop_id` yet or no Etsy app
     *     key pair -- both ordinary states short of `setup`/`auth etsy`, and the
     *     frontend falls back to a plain text field exactly like it did before this
     *     endpoint existed.
     */
    get: operations["list_etsy_sections_api_etsy_sections_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/garment-profiles": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Garment Profiles */
    get: operations["list_garment_profiles_api_garment_profiles_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Health */
    get: operations["health_api_health_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/listing-designs": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Listing Designs */
    get: operations["list_listing_designs_api_listing_designs_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/listing-designs/{name}/thumbnail": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Listing Design Thumbnail
     * @description The artwork itself, downscaled -- what the listings table, its hover
     *     card and the editor's design strip all show.
     *
     *     Distinct from ``designs.py``'s calibrator library for the same reason
     *     ``GET /api/listing-designs`` is: ``designs/`` holds artwork that ships,
     *     ``test-designs/`` holds calibration targets, and a listing's design is
     *     never one of the latter.
     *
     *     An unusable *name* needs nothing here: ``InvalidNameError`` out of
     *     ``design_file`` becomes a 400 through the app-wide handler in ``app.py``.
     */
    get: operations["listing_design_thumbnail_api_listing_designs__name__thumbnail_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/listing-draft": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Listing Draft
     * @description The listing `+ New listing` opens the editor on, before it has a name.
     *
     *     There is no separate create *form* -- the editor itself is the form, and a
     *     listing is written the moment it is named and priced. What the editor needs
     *     first is a document to render, and inventing one in the browser would put
     *     the starting shape of a listing in two places, so the server hands over
     *     `EMPTY_DRAFT`: nothing chosen, nothing invented, and a block issue for each
     *     thing still to pick.
     *
     *     ``name`` comes back empty, which is exactly the state the editor refuses to
     *     save in.
     */
    get: operations["listing_draft_api_listing_draft_get"];
    put?: never;
    /**
     * Describe Listing Draft
     * @description The same, for a candidate the editor has since edited. Writes nothing.
     *
     *     The mount-time draft above answers once; this is what keeps the issues
     *     banner true for every edit made before the listing has a name. Without it
     *     the banner would still be saying "no colours enabled" about a listing whose
     *     colours were picked a minute ago -- and the banner is the only way an
     *     unsaved listing can be told what it is still missing.
     */
    post: operations["describe_listing_draft_api_listing_draft_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/listings": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Listings
     * @description Every listing, with its status resolved in **one** Etsy round trip for
     *     the whole table rather than one per row -- which is why the live fact is
     *     gathered here and handed down rather than looked up per listing.
     */
    get: operations["list_listings_api_listings_get"];
    put?: never;
    /**
     * Create Listing
     * @description Naming a listing is what creates it.
     *
     *     Mirrors PATCH exactly, one level up: a document that fails
     *     ``Listing.model_validate`` is a **200** carrying ``field_errors`` with
     *     nothing written, so the editor never has to branch on a status code to show
     *     inline validation. The two things a *name* can be wrong about keep their
     *     status codes instead -- not a single path segment is the 400 `_segment`
     *     raises through `listing_file`, and already taken is a 409.
     *
     *     That 409 tests the **directory**, not ``listing.yaml``: a `listings/{name}/`
     *     left behind with a `state.lock.json` and no document would otherwise be
     *     written into, and the new listing would inherit another one's
     *     ``etsy_listing_id``.
     */
    post: operations["create_listing_api_listings_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/listings/{name}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Listing */
    get: operations["get_listing_api_listings__name__get"];
    put?: never;
    post?: never;
    /**
     * Delete Listing
     * @description Delete from the listings table (PRD 63, 66).
     *
     *     No remotes: wipe now. Remotes: write ``lifecycle: deleted`` and leave the
     *     row pending. Published: 409 -- retire it instead. Confirm is the UI's.
     */
    delete: operations["delete_listing_api_listings__name__delete"];
    options?: never;
    head?: never;
    /** Patch Listing */
    patch: operations["patch_listing_api_listings__name__patch"];
    trace?: never;
  };
  "/api/listings/{name}/previews/{template}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Listing Preview
     * @description A ``multiple``/``single``-kind scene: no per-colour photo, so no
     *     colour segment (PRD 28's rule, mirrored from ``render_file``).
     */
    get: operations["listing_preview_api_listings__name__previews__template__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/listings/{name}/previews/{template}/{colour}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Listing Preview Coloured
     * @description A ``colour-matrix``-kind scene: one preview per colour.
     */
    get: operations["listing_preview_coloured_api_listings__name__previews__template___colour__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/listings/{name}/rename": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Rename Listing
     * @description Move a listing, whole, to a new name.
     *
     *     A listing's identity is its directory name (PRD 60), so the rename is a
     *     directory move: ``listing.yaml``, ``state.lock.json`` and Phase 4's
     *     generated copy travel together, and `.cache/renders/{name}/` moves with them
     *     because the render cache is keyed by listing name too -- left behind it
     *     would orphan a tree nothing deletes and cost a full re-render.
     *
     *     The lockfile's ``outputs`` keys still spell the old path afterwards, and are
     *     left that way deliberately: nothing reads them, they become true again at
     *     the next apply, and rewriting them here would breach "only the lockfile
     *     merges a lockfile".
     *
     *     POST rather than PUT: the body is neither the listing nor its new
     *     representation, and a second call 404s. `POST /api/templates/{name}/kind` is
     *     the same shape.
     */
    post: operations["rename_listing_api_listings__name__rename_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/pricing-plans": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Pricing Plans
     * @description Every plan, each flagged for whether it was built for this garment.
     *
     *     ``garment_profile`` is optional because a listing that has not chosen one
     *     yet has nothing to be compatible *with*: asking with an empty name says that
     *     honestly, and the editor then drops the "different garment" note rather than
     *     labelling every plan as differing from a garment nobody picked.
     */
    get: operations["list_pricing_plans_api_pricing_plans_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/runs": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Runs
     * @description ``listing`` narrows to that listing's current run (active, or finished
     *     and not yet superseded -- decision 7's retention). Omitted, every run this
     *     process still remembers, for a future workspace-wide view.
     */
    get: operations["list_runs_api_runs_get"];
    put?: never;
    /**
     * Create Run
     * @description A ``409`` names the run already holding one of these listings, so the
     *     caller can reattach to it (``GET /api/runs/{active_run}``) instead of
     *     retrying into the same refusal.
     */
    post: operations["create_run_api_runs_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/runs/{run_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Run */
    get: operations["get_run_api_runs__run_id__get"];
    put?: never;
    post?: never;
    /**
     * Cancel Run
     * @description Cancel a queued or running **plan**. An ``apply`` is refused
     *     unconditionally (decision 8: Back leaves, it never cancels one), and so is
     *     a run that has already finished.
     */
    delete: operations["cancel_run_api_runs__run_id__delete"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/runs/{run_id}/events": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Stream Events
     * @description ``text/event-stream`` over this run's own event buffer -- every event
     *     already recorded past ``Last-Event-ID``, then whatever the worker thread
     *     appends next, until the run reaches a terminal phase.
     */
    get: operations["stream_events_api_runs__run_id__events_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/runs/{run_id}/seen": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Mark Seen */
    post: operations["mark_seen_api_runs__run_id__seen_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/templates": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Templates */
    get: operations["list_templates_api_templates_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/templates/{name}/colour-report": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Colour Report
     * @description What each photo will be taken as if this becomes a colour-matrix set.
     *
     *     Shown in the kind picker before committing, so a badly named file is seen
     *     while it is still cheap to think about. A row with ``clean: false`` is one
     *     ``assign_kind`` will rename on disk (PRD 7a: the filename *is* the
     *     slugified colour, and a directory whose filenames disagree with the
     *     colours they mean is the state that rule exists to prevent).
     */
    get: operations["colour_report_api_templates__name__colour_report_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/templates/{name}/config": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Config */
    get: operations["get_config_api_templates__name__config_get"];
    /** Put Config */
    put: operations["put_config_api_templates__name__config_put"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/templates/{name}/design-preview": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Design Preview
     * @description A listing's *real* artwork, composited onto this template's saved
     *     geometry -- what the listing editor's Variants/Listing Images tabs show
     *     so a colour can be judged against the actual design, not a bare photo.
     *
     *     ``design`` is a name from ``GET /api/listing-designs``, resolved through
     *     ``Workspace.design_file`` -- deliberately not :func:`resolve_design`,
     *     which is the calibrator's own test-design library and never sees a
     *     listing's real artwork.
     */
    get: operations["design_preview_api_templates__name__design_preview_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/templates/{name}/kind": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Assign Kind
     * @description The first calibration step: say what this template is, and get the
     *     starting ``template.yaml`` for that shape.
     *
     *     Refuses a template that already has a config. Kind decides the whole file
     *     shape (A11), so changing it would discard whatever calibration was done in
     *     the old shape's fields -- and doing that silently, from a picker, is the
     *     kind of data loss nobody would think to look for.
     */
    post: operations["assign_kind_api_templates__name__kind_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/templates/{name}/photo": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Photo
     * @description The template's own photo, at its own resolution -- the bare-scene
     *     counterpart of ``GET .../design-preview`` for a listing that has not
     *     picked a design yet.
     *
     *     Same photo :func:`thumbnail` serves, same resolution rule
     *     (:func:`_thumbnail_source`), just not downscaled to list size: the
     *     listing editor's Variants and Listing Images previews are a large hero
     *     stage, not a row of tiles, and serving them the 160px list thumbnail is
     *     why that stage used to look tiny for a listing with no design picked yet.
     */
    get: operations["photo_api_templates__name__photo_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/templates/{name}/preview": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Preview */
    post: operations["preview_api_templates__name__preview_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/templates/{name}/swatch": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Swatch
     * @description This colour's real garment shade, for a quick-glance dot next to its
     *     name -- the median pixel (`sample_swatch`) inside the saved bounding box
     *     of the colour's own scene photo, not an invented hex value. Only a
     *     ``colour-matrix`` template has one photo per colour to sample; any other
     *     kind 404s the same way a photo-less colour does.
     */
    get: operations["swatch_api_templates__name__swatch_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/templates/{name}/thumbnail": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Thumbnail
     * @description The template's own photo, downscaled, for the rail.
     *
     *     Not a render: the rail shows every template in the workspace at once, and
     *     running the real pipeline once per row would make opening the calibrator
     *     cost as much as calibrating. Which photo is shown is
     *     :meth:`~etsy_listings.workspace.workspace.Workspace.template_preview_photo`'s
     *     question, not this endpoint's.
     *
     *     ``colour`` narrows that to one photo of a ``colour-matrix`` set, for
     *     callers that are showing a *particular* variant rather than standing in
     *     for the template: the listings editor's reel draws one tile per
     *     ``media`` entry, and without this every colour of a set drew the same
     *     picture, since ``template_preview_photo`` deliberately answers "any one
     *     of them". Resolution goes through
     *     :meth:`~etsy_listings.workspace.workspace.Workspace.template_base_image`,
     *     which owns PRD 7a's filename convention and its trailing-segment
     *     fallback -- this endpoint must not glob for ``{colour}.png`` itself.
     *
     *     How it is downscaled and served is :mod:`etsy_listings.ui.api.thumbnails`'
     *     question -- the listings table asks the same one of a design.
     */
    get: operations["thumbnail_api_templates__name__thumbnail_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/workspace": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Workspace */
    get: operations["get_workspace_api_workspace_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/{full_path}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Spa Fallback */
    get: operations["spa_fallback__full_path__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** ActionDTO */
    ActionDTO: {
      /** Description */
      description: string;
      /** Inputs */
      inputs: string[];
      /** Missing Outputs */
      missing_outputs: string[];
      /** Outputs */
      outputs: string[];
    };
    /** AssignKindRequest */
    AssignKindRequest: {
      /**
       * Kind
       * @enum {string}
       */
      kind: "colour-matrix" | "multiple" | "single";
    };
    /** Body_upload_design_api_designs_post */
    Body_upload_design_api_designs_post: {
      /** File */
      file: string;
    };
    /**
     * ColourMatrixPreviewRequest
     * @description Disambiguated from the other two preview shapes by required fields
     *     alone (``colour`` here, ``placements`` on ``MultiplePreviewRequest``,
     *     neither on ``SinglePreviewRequest``) -- extra fields are ignored rather
     *     than forbidden, since a natural client pattern is spreading a whole
     *     ``GET .../config`` response (which includes ``kind``) into the body.
     */
    ColourMatrixPreviewRequest: {
      /** Bounding Box */
      bounding_box: [
        components["schemas"]["Point"],
        components["schemas"]["Point"],
        components["schemas"]["Point"],
        components["schemas"]["Point"],
      ];
      /** Colour */
      colour: string;
      /**
       * Design
       * @default bundled-grid
       */
      design: string;
      /**
       * @default {
       *       "enabled": false,
       *       "strength": 0
       *     }
       */
      displace: components["schemas"]["DisplaceConfig"];
      /**
       * @default {
       *       "blend": "soft-light",
       *       "enabled": true,
       *       "opacity": 0.6
       *     }
       */
      shade: components["schemas"]["ShadeConfig"];
    };
    /**
     * ColourMatrixTemplate
     * @description One photo per colour, same design position in all of them. Scene
     *     images are ``{colour-slug}.png`` per colour (PRD 7a) -- there is no
     *     ``colours:`` list in the YAML, since the filenames present in the
     *     directory *are* the colour set.
     */
    ColourMatrixTemplate: {
      /** Bounding Box */
      bounding_box: [
        components["schemas"]["Point"],
        components["schemas"]["Point"],
        components["schemas"]["Point"],
        components["schemas"]["Point"],
      ];
      /**
       * @default {
       *       "enabled": false,
       *       "strength": 0
       *     }
       */
      displace: components["schemas"]["DisplaceConfig"];
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      kind: "colour-matrix";
      /**
       * @default {
       *       "blend": "soft-light",
       *       "enabled": true,
       *       "opacity": 0.6
       *     }
       */
      shade: components["schemas"]["ShadeConfig"];
    };
    /**
     * ColourReportRow
     * @description What one photo in a candidate ``colour-matrix`` set will be taken as.
     *
     *     Reporting only: PRD 7a makes the filename the source of truth, so there is
     *     no manual mapping to offer and nothing here changes a name.
     */
    ColourReportRow: {
      /** Clean */
      clean: boolean;
      /** Colour */
      colour: string;
      /** Filename */
      filename: string;
    };
    /**
     * CommonMediaSummary
     * @description One shared asset under ``common-media/`` -- the other half of `media:`,
     *     a bare path rather than a rendered mockup.
     */
    CommonMediaSummary: {
      /** File */
      file: string;
      /** Name */
      name: string;
      /** Ref */
      ref: string;
    };
    /**
     * CreateListingRequest
     * @description The whole document, not a handful of fields to build one from.
     *
     *     The editor is the create form, so by the time a name is typed the user may
     *     have chosen a design, colours and images -- and the shape they edited is the
     *     shape that should be written. A server-built stub here would be a second
     *     opinion about what a new listing starts as.
     */
    CreateListingRequest: {
      /** Document */
      document: {
        [key: string]: unknown;
      };
      /** Name */
      name: string;
    };
    /** CreateRunRequest */
    CreateRunRequest: {
      /** Expect */
      expect?: {
        [key: string]: string;
      } | null;
      /**
       * Kind
       * @enum {string}
       */
      kind: "plan" | "apply";
      /** Listings */
      listings: string[];
    };
    /**
     * DesignSummary
     * @description One entry in the calibrator's test-design library (A19).
     *
     *     ``bundled-grid``: the grid/ruler target, for spotting warp/displacement
     *     errors. ``bundled-on-light``/``bundled-on-dark``: deterministic
     *     ink-coloured targets, so a mis-resolved artwork is visually obvious in the
     *     calibrator, not just described in a diff. ``upload``: a PNG the user added,
     *     for judging a real ink weight on a real garment -- the question the grid
     *     cannot answer.
     */
    DesignSummary: {
      /** Id */
      id: string;
      /** Label */
      label: string;
      /**
       * Source
       * @enum {string}
       */
      source: "bundled" | "upload";
    };
    /**
     * DisplaceConfig
     * @description PRD: implemented but off by default -- over-strong displacement looks
     *     melted, so it's tuned per template in the calibrator's live preview.
     */
    DisplaceConfig: {
      /**
       * Enabled
       * @default false
       */
      enabled: boolean;
      /**
       * Strength
       * @default 0
       */
      strength: number;
    };
    /**
     * DraftListingRequest
     * @description A candidate ``listing.yaml``, as the editor holds it before the listing
     *     exists.
     *
     *     ``dict`` rather than ``Listing``, deliberately: an incomplete candidate is
     *     the *normal* case on this endpoint, and rejecting it at the FastAPI boundary
     *     would answer with a 422 the editor cannot render. The point is to get it as
     *     far as ``Listing.draft`` and report what is missing.
     */
    DraftListingRequest: {
      /** Document */
      document?: {
        [key: string]: unknown;
      };
    };
    /** DriftDTO */
    DriftDTO: {
      /** Last Applied */
      last_applied: unknown;
      /** Last Applied Label */
      last_applied_label?: string | null;
      /** Live */
      live: unknown;
      /** Live Label */
      live_label?: string | null;
      /** Path */
      path: string;
    };
    /** EtsyListingConfig */
    EtsyListingConfig: {
      /**
       * Description
       * @default <generate>
       */
      description: string;
      /**
       * Materials
       * @default []
       */
      materials: string[];
      /** Renewal */
      renewal?: ("manual" | "auto") | null;
      /** Section */
      section?: string | null;
      /** Shipping Profile */
      shipping_profile?: string | null;
      /**
       * Tags
       * @default <generate>
       */
      tags: string[] | "<generate>";
      /**
       * Title
       * @default <generate>
       */
      title: string;
      /** Variation Images */
      variation_images?: string | null;
    };
    /**
     * EtsySectionSummary
     * @description One row for the Details tab's Section dropdown, from
     *     `EtsyShopClient.shop_sections` -- unscoped, so this needs only the
     *     workspace's app key pair, never a signed-in Etsy session.
     */
    EtsySectionSummary: {
      /** Id */
      id: number;
      /** Title */
      title: string;
    };
    /** FieldChangeDTO */
    FieldChangeDTO: {
      /** After */
      after: unknown;
      /** Before */
      before: unknown;
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      kind: "field";
      /** Path */
      path: string;
    };
    /** GarmentProfileSummary */
    GarmentProfileSummary: {
      /** Colors */
      colors: {
        [key: string]: "light" | "dark";
      };
      /** Name */
      name: string;
      /** Preview Template */
      preview_template?: string | null;
      /** Sizes */
      sizes: string[];
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** Issue */
    Issue: {
      /** Message */
      message: string;
      /**
       * Severity
       * @enum {string}
       */
      severity: "block" | "warn";
      /**
       * Tab
       * @enum {string}
       */
      tab: "variants" | "images" | "details";
      /** Where */
      where: string;
    };
    /** IssueCounts */
    IssueCounts: {
      /** Block */
      block: number;
      /** Warn */
      warn: number;
    };
    /** ListChangeDTO */
    ListChangeDTO: {
      /** Added */
      added: unknown[];
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      kind: "list";
      /** Path */
      path: string;
      /** Removed */
      removed: unknown[];
      /** Reordered */
      reordered: boolean;
    };
    /** ListingDesignSummary */
    ListingDesignSummary: {
      /** File */
      file: string;
      /** Name */
      name: string;
    };
    /**
     * ListingDetail
     * @description The full `Listing`, plus what the editor needs and nothing a listing
     *     itself would ever store: computed status, computed issues, and (only
     *     meaningful right after a PATCH) which fields a rejected candidate failed
     *     on.
     */
    ListingDetail: {
      /**
       * Artwork
       * @default {}
       */
      artwork: {
        [key: string]: string;
      };
      /** Brief */
      brief: string;
      /** Colors */
      colors: string[];
      /** Design */
      design: {
        [key: string]: string;
      };
      /**
       * @default {
       *       "description": "<generate>",
       *       "materials": [],
       *       "tags": "<generate>",
       *       "title": "<generate>"
       *     }
       */
      etsy: components["schemas"]["EtsyListingConfig"];
      /** Etsy Listing Id */
      etsy_listing_id?: number | null;
      /**
       * Field Errors
       * @default {}
       */
      field_errors: {
        [key: string]: string;
      };
      /** Garment Profile */
      garment_profile: string;
      /** Issues */
      issues: components["schemas"]["Issue"][];
      /** Lifecycle */
      lifecycle?: ("retired" | "deleted" | "renew") | null;
      /** Media */
      media: (components["schemas"]["TemplateMediaEntry"] | string)[];
      /** Modified At */
      modified_at: string | null;
      /** Name */
      name: string;
      /**
       * Price Overrides
       * @default {}
       */
      price_overrides: {
        [key: string]: {
          [key: string]: string;
        };
      };
      /**
       * Prices
       * @default {}
       */
      prices: {
        [key: string]: string;
      };
      /** Pricing Plan */
      pricing_plan?: string | null;
      /** Pricing Plan Name */
      pricing_plan_name?: string | null;
      /** Printify Product Id */
      printify_product_id?: string | null;
      /**
       * Resolved Prices
       * @default []
       */
      resolved_prices: components["schemas"]["ResolvedPrice"][];
      /**
       * Status
       * @enum {string}
       */
      status:
        | "draft"
        | "deployed"
        | "live"
        | "dirty"
        | "pending-delete"
        | "pending-retire"
        | "inactive"
        | "expired";
    };
    /**
     * ListingFailedEvent
     * @description The run's ``RunObserver.on_failure`` twin. ``message`` is the
     *     :class:`~etsy_listings.errors.UserFacingError`'s own text, word for word
     *     (decision 5) -- never the generic internal-error text, which belongs to a
     *     :class:`PhaseEvent` naming the whole run ``failed`` instead, since a
     *     defect is not about any one listing. ``stale_plan`` is set only when the
     *     error was a :class:`~etsy_listings.engine.run.StalePlanError`.
     */
    ListingFailedEvent: {
      /** Id */
      id: number;
      /** Listing */
      listing: string;
      /** Message */
      message: string;
      stale_plan?: components["schemas"]["PlanDTO"] | null;
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: "listing_failed";
    };
    /** ListingPlannedEvent */
    ListingPlannedEvent: {
      /** Fingerprint */
      fingerprint: string;
      /** Id */
      id: number;
      /** Listing */
      listing: string;
      plan: components["schemas"]["PlanDTO"];
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: "listing_planned";
    };
    /** ListingSummary */
    ListingSummary: {
      /** Colour Count */
      colour_count: number;
      /** Design */
      design: string | null;
      /** Etsy Listing Id */
      etsy_listing_id?: number | null;
      /** Garment Profile */
      garment_profile: string;
      /**
       * Gestures
       * @default []
       */
      gestures: ("delete" | "retire" | "un-retire" | "cancel" | "renew")[];
      issue_counts: components["schemas"]["IssueCounts"];
      /** Name */
      name: string;
      /** Printify Product Id */
      printify_product_id?: string | null;
      /**
       * Status
       * @enum {string}
       */
      status:
        | "draft"
        | "deployed"
        | "live"
        | "dirty"
        | "pending-delete"
        | "pending-retire"
        | "inactive"
        | "expired";
    };
    /** MediaChangeDTO */
    MediaChangeDTO: {
      /** After */
      after: string | null;
      /** Before */
      before: string | null;
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      kind: "media";
      /** Rank */
      rank: number;
    };
    /** MultiplePreviewRequest */
    MultiplePreviewRequest: {
      /**
       * Design
       * @default bundled-grid
       */
      design: string;
      /**
       * @default {
       *       "enabled": false,
       *       "strength": 0
       *     }
       */
      displace: components["schemas"]["DisplaceConfig"];
      /** Placements */
      placements: components["schemas"]["Placement"][];
      /**
       * @default {
       *       "blend": "soft-light",
       *       "enabled": true,
       *       "opacity": 0.6
       *     }
       */
      shade: components["schemas"]["ShadeConfig"];
    };
    /**
     * MultipleTemplate
     * @description Several garments in one photo. ``displace``/``shade`` are scene-level
     *     only -- one photo, one lighting pass; a placement needing different
     *     rendering treatment belongs in its own template instead.
     */
    MultipleTemplate: {
      /**
       * Colour Coverage
       * @default exact
       * @enum {string}
       */
      colour_coverage: "exact" | "subset";
      /**
       * @default {
       *       "enabled": false,
       *       "strength": 0
       *     }
       */
      displace: components["schemas"]["DisplaceConfig"];
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      kind: "multiple";
      /** Placements */
      placements: components["schemas"]["Placement"][];
      /**
       * @default {
       *       "blend": "soft-light",
       *       "enabled": true,
       *       "opacity": 0.6
       *     }
       */
      shade: components["schemas"]["ShadeConfig"];
    };
    /**
     * PhaseEvent
     * @description The run (or one of the two run kinds) moved to a new phase. Always the
     *     first event of a run and always its last, whichever phase that turns out
     *     to be (A33, decision 7).
     */
    PhaseEvent: {
      /** Id */
      id: number;
      /**
       * Phase
       * @enum {string}
       */
      phase:
        | "queued"
        | "planning"
        | "planned"
        | "previewing"
        | "ready"
        | "applying"
        | "applied"
        | "failed"
        | "stale"
        | "cancelled";
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: "phase";
    };
    /**
     * Placement
     * @description One garment within a ``multiple``-kind scene.
     */
    Placement: {
      /** Artwork */
      artwork?: string | null;
      /** Bounding Box */
      bounding_box: [
        components["schemas"]["Point"],
        components["schemas"]["Point"],
        components["schemas"]["Point"],
        components["schemas"]["Point"],
      ];
      /** Colour */
      colour: string;
    };
    /** PlanDTO */
    PlanDTO: {
      /** Etsy Listing Id */
      etsy_listing_id: number | null;
      /** Is Live */
      is_live: boolean;
      /** Listing */
      listing: string;
      /** Stage Plans */
      stage_plans: components["schemas"]["StagePlanDTO"][];
    };
    /** Point */
    Point: {
      /** X */
      x: number;
      /** Y */
      y: number;
    };
    /** PreviewRenderedEvent */
    PreviewRenderedEvent: {
      /** Colour */
      colour: string | null;
      /** Id */
      id: number;
      /** Listing */
      listing: string;
      /** Template */
      template: string;
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: "preview_rendered";
    };
    /** PriceChangeDTO */
    PriceChangeDTO: {
      /** After */
      after: string;
      /** Before */
      before: string;
      /** Color */
      color?: string | null;
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      kind: "price";
      /** Size */
      size: string;
    };
    /** PricingPlanSummary */
    PricingPlanSummary: {
      /** Compatible */
      compatible: boolean;
      /** Garment Profile */
      garment_profile: string;
      /** Name */
      name: string;
      /** Ref */
      ref: string;
    };
    /**
     * ProgressEvent
     * @description ``ctx.emit``'s ``Event``, tagged with whatever stage
     *     :class:`StageApplyingEvent` last named for this listing -- no stage
     *     changes how it reports progress (A33, decision 7).
     */
    ProgressEvent: {
      /** Id */
      id: number;
      /** Listing */
      listing: string;
      /** Message */
      message: string;
      /** Stage */
      stage: string | null;
      /**
       * Swatches
       * @default []
       */
      swatches: [number, number, number][];
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: "progress";
    };
    /** RenameListingRequest */
    RenameListingRequest: {
      /** New Name */
      new_name: string;
    };
    /** ResolvedPrice */
    ResolvedPrice: {
      /** Amount */
      amount: string;
      /** Size */
      size: string;
    };
    /** RunDetail */
    RunDetail: {
      /** Events */
      events: (
        | components["schemas"]["PhaseEvent"]
        | components["schemas"]["StageCheckingEvent"]
        | components["schemas"]["StagePlannedEvent"]
        | components["schemas"]["ListingPlannedEvent"]
        | components["schemas"]["PreviewRenderedEvent"]
        | components["schemas"]["StageApplyingEvent"]
        | components["schemas"]["ProgressEvent"]
        | components["schemas"]["StageAppliedEvent"]
        | components["schemas"]["StageFailedEvent"]
        | components["schemas"]["ListingFailedEvent"]
      )[];
      /** Id */
      id: string;
      /**
       * Kind
       * @enum {string}
       */
      kind: "plan" | "apply";
      /** Listings */
      listings: string[];
      /**
       * Phase
       * @enum {string}
       */
      phase:
        | "queued"
        | "planning"
        | "planned"
        | "previewing"
        | "ready"
        | "applying"
        | "applied"
        | "failed"
        | "stale"
        | "cancelled";
      /** Seen */
      seen: boolean;
    };
    /**
     * RunSummary
     * @description Enough to show a page-head control (decision 8's table) or a row in a
     *     future batch view -- everything except the event log itself.
     */
    RunSummary: {
      /** Id */
      id: string;
      /**
       * Kind
       * @enum {string}
       */
      kind: "plan" | "apply";
      /** Listings */
      listings: string[];
      /**
       * Phase
       * @enum {string}
       */
      phase:
        | "queued"
        | "planning"
        | "planned"
        | "previewing"
        | "ready"
        | "applying"
        | "applied"
        | "failed"
        | "stale"
        | "cancelled";
      /** Seen */
      seen: boolean;
    };
    /**
     * ShadeConfig
     * @description Blends the base mockup photo's own greyscale lighting over the printed
     *     design, so a flat design picks up the garment's real fold shadows and
     *     light falloff instead of looking pasted on as a flat rectangle -- this is
     *     why a plain flat-lay PNG is enough to mock up, with no purchased
     *     Photoshop lighting map needed. On by default: almost every mockup needs
     *     it. ``multiply`` crushes prints on dark garments, so ``soft-light`` or a
     *     mid-grey pivot is used for those instead.
     */
    ShadeConfig: {
      /**
       * Blend
       * @default soft-light
       * @enum {string}
       */
      blend: "multiply" | "soft-light" | "grey-pivot";
      /**
       * Enabled
       * @default true
       */
      enabled: boolean;
      /**
       * Opacity
       * @default 0.6
       */
      opacity: number;
    };
    /** SinglePreviewRequest */
    SinglePreviewRequest: {
      /** Bounding Box */
      bounding_box: [
        components["schemas"]["Point"],
        components["schemas"]["Point"],
        components["schemas"]["Point"],
        components["schemas"]["Point"],
      ];
      /**
       * Design
       * @default bundled-grid
       */
      design: string;
      /**
       * @default {
       *       "enabled": false,
       *       "strength": 0
       *     }
       */
      displace: components["schemas"]["DisplaceConfig"];
      /**
       * @default {
       *       "blend": "soft-light",
       *       "enabled": true,
       *       "opacity": 0.6
       *     }
       */
      shade: components["schemas"]["ShadeConfig"];
    };
    /**
     * SingleTemplate
     * @description One photo, one garment -- a lifestyle shot, a folded product photo,
     *     anything that isn't part of a colour set.
     */
    SingleTemplate: {
      /** Artwork */
      artwork?: string | null;
      /** Bounding Box */
      bounding_box: [
        components["schemas"]["Point"],
        components["schemas"]["Point"],
        components["schemas"]["Point"],
        components["schemas"]["Point"],
      ];
      /** Colour */
      colour?: string | null;
      /**
       * @default {
       *       "enabled": false,
       *       "strength": 0
       *     }
       */
      displace: components["schemas"]["DisplaceConfig"];
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      kind: "single";
      /**
       * @default {
       *       "blend": "soft-light",
       *       "enabled": true,
       *       "opacity": 0.6
       *     }
       */
      shade: components["schemas"]["ShadeConfig"];
    };
    /** StageAppliedEvent */
    StageAppliedEvent: {
      /** Id */
      id: number;
      /** Listing */
      listing: string;
      /** Stage */
      stage: string;
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: "stage_applied";
    };
    /** StageApplyingEvent */
    StageApplyingEvent: {
      /** Id */
      id: number;
      /** Listing */
      listing: string;
      /** Stage */
      stage: string;
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: "stage_applying";
    };
    /** StageCheckingEvent */
    StageCheckingEvent: {
      /** Id */
      id: number;
      /** Listing */
      listing: string;
      /** Stage */
      stage: string;
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: "stage_checking";
    };
    /** StageFailedEvent */
    StageFailedEvent: {
      /** Id */
      id: number;
      /** Listing */
      listing: string;
      /** Message */
      message: string;
      /** Stage */
      stage: string;
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: "stage_failed";
    };
    /** StagePlanDTO */
    StagePlanDTO: {
      /**
       * Actions
       * @default []
       */
      actions: components["schemas"]["ActionDTO"][];
      /** Blocked */
      blocked?: string | null;
      /**
       * Changes
       * @default []
       */
      changes: (
        | components["schemas"]["FieldChangeDTO"]
        | components["schemas"]["ListChangeDTO"]
        | components["schemas"]["PriceChangeDTO"]
        | components["schemas"]["MediaChangeDTO"]
      )[];
      /**
       * Drift
       * @default []
       */
      drift: components["schemas"]["DriftDTO"][];
      /** Reason */
      reason?: string | null;
      /** Snapshot */
      snapshot?: {
        [key: string]: unknown;
      } | null;
      /** Stage */
      stage: string;
      /** Will Run */
      will_run: boolean;
    };
    /** StagePlannedEvent */
    StagePlannedEvent: {
      /** Id */
      id: number;
      /** Listing */
      listing: string;
      stage_plan: components["schemas"]["StagePlanDTO"];
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: "stage_planned";
    };
    /**
     * SwatchResponse
     * @description A colour-matrix colour's real garment shade, sampled off its own scene
     *     photo (`render/swatch.py`'s `sample_swatch`) rather than an invented or
     *     hand-typed hex value -- nothing in the domain model stores one.
     */
    SwatchResponse: {
      /** Hex */
      hex: string;
    };
    /**
     * TemplateMediaEntry
     * @description Always-explicit template reference -- there is no bare-colour
     *     shorthand. ``colour`` is required when the referenced template is
     *     ``colour-matrix`` kind (which colour's photo) and must be omitted for
     *     ``multiple``/``single`` kind (exactly one output each, nothing to
     *     disambiguate).
     */
    TemplateMediaEntry: {
      /** Colour */
      colour?: string | null;
      /** Template */
      template: string;
    };
    /**
     * TemplatePhoto
     * @description One scene photo in a template's directory: which colour it is, and where
     *     it actually is.
     *
     *     ``file`` is workspace-relative and forward-slashed, resolved through
     *     ``Workspace.scene_photo`` -- the same rule the renderer uses, including the
     *     trailing-segment fallback for a vendor pack delivered as
     *     ``{template}-{colour}.png``. The listings editor shows it under its preview
     *     so the user knows which file to go and edit, and it used to *derive* that
     *     caption from PRD 7a's convention in TypeScript, which named a file that was
     *     not there for exactly the pack the fallback exists for.
     *
     *     ``colour`` is ``None`` for a ``multiple``/``single`` template's fixed
     *     ``scene.png``: there is no per-colour name to derive one from (PRD 28).
     */
    TemplatePhoto: {
      /** Colour */
      colour: string | null;
      /** File */
      file: string;
    };
    /** TemplateSummary */
    TemplateSummary: {
      /** Colours */
      colours: string[];
      /** Has Config */
      has_config: boolean;
      /** Height */
      height?: number | null;
      /** Kind */
      kind: ("colour-matrix" | "multiple" | "single") | null;
      /** Name */
      name: string;
      /**
       * Photos
       * @default []
       */
      photos: components["schemas"]["TemplatePhoto"][];
      /**
       * Status
       * @enum {string}
       */
      status: "needs-calibration" | "calibrated";
      /** Status Reason */
      status_reason?: string | null;
      /** Width */
      width?: number | null;
    };
    /** ValidationError */
    ValidationError: {
      /** Context */
      ctx?: Record<string, never>;
      /** Input */
      input?: unknown;
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
    /**
     * WorkspaceSummary
     * @description Which workspace the UI is pointed at. One workspace is one shop, so the
     *     sidebar names it -- the difference between a test shop and the real one is
     *     worth seeing before an edit, not after an apply.
     */
    WorkspaceSummary: {
      /** Shop Name */
      shop_name: string | null;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  list_common_media_api_common_media_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CommonMediaSummary"][];
        };
      };
    };
  };
  common_media_file_api_common_media__name__file_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        name: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  common_media_thumbnail_api_common_media__name__thumbnail_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        name: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_designs_api_designs_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DesignSummary"][];
        };
      };
    };
  };
  upload_design_api_designs_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "multipart/form-data": components["schemas"]["Body_upload_design_api_designs_post"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DesignSummary"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_etsy_sections_api_etsy_sections_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EtsySectionSummary"][];
        };
      };
    };
  };
  list_garment_profiles_api_garment_profiles_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GarmentProfileSummary"][];
        };
      };
    };
  };
  health_api_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: string;
          };
        };
      };
    };
  };
  list_listing_designs_api_listing_designs_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ListingDesignSummary"][];
        };
      };
    };
  };
  listing_design_thumbnail_api_listing_designs__name__thumbnail_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        name: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  listing_draft_api_listing_draft_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ListingDetail"];
        };
      };
    };
  };
  describe_listing_draft_api_listing_draft_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["DraftListingRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ListingDetail"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_listings_api_listings_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ListingSummary"][];
        };
      };
    };
  };
  create_listing_api_listings_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateListingRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ListingDetail"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_listing_api_listings__name__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        name: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ListingDetail"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  delete_listing_api_listings__name__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        name: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  patch_listing_api_listings__name__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        name: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          [key: string]: unknown;
        };
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ListingDetail"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  listing_preview_api_listings__name__previews__template__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        template: string;
        name: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  listing_preview_coloured_api_listings__name__previews__template___colour__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        template: string;
        colour: string;
        name: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  rename_listing_api_listings__name__rename_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        name: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RenameListingRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ListingDetail"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_pricing_plans_api_pricing_plans_get: {
    parameters: {
      query?: {
        garment_profile?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PricingPlanSummary"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_runs_api_runs_get: {
    parameters: {
      query?: {
        listing?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RunSummary"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  create_run_api_runs_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateRunRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RunSummary"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_run_api_runs__run_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        run_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RunDetail"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  cancel_run_api_runs__run_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        run_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RunSummary"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  stream_events_api_runs__run_id__events_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        run_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  mark_seen_api_runs__run_id__seen_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        run_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RunSummary"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_templates_api_templates_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TemplateSummary"][];
        };
      };
    };
  };
  colour_report_api_templates__name__colour_report_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        name: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ColourReportRow"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_config_api_templates__name__config_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        name: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json":
            | components["schemas"]["ColourMatrixTemplate"]
            | components["schemas"]["MultipleTemplate"]
            | components["schemas"]["SingleTemplate"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  put_config_api_templates__name__config_put: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        name: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json":
          | components["schemas"]["ColourMatrixTemplate"]
          | components["schemas"]["MultipleTemplate"]
          | components["schemas"]["SingleTemplate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json":
            | components["schemas"]["ColourMatrixTemplate"]
            | components["schemas"]["MultipleTemplate"]
            | components["schemas"]["SingleTemplate"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  design_preview_api_templates__name__design_preview_get: {
    parameters: {
      query: {
        design: string;
        colour?: string | null;
        scale?: "editor" | "full";
      };
      header?: never;
      path: {
        name: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  assign_kind_api_templates__name__kind_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        name: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AssignKindRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json":
            | components["schemas"]["ColourMatrixTemplate"]
            | components["schemas"]["MultipleTemplate"]
            | components["schemas"]["SingleTemplate"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  photo_api_templates__name__photo_get: {
    parameters: {
      query?: {
        colour?: string | null;
      };
      header?: never;
      path: {
        name: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  preview_api_templates__name__preview_post: {
    parameters: {
      query?: {
        scale?: "editor" | "full";
      };
      header?: never;
      path: {
        name: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json":
          | components["schemas"]["ColourMatrixPreviewRequest"]
          | components["schemas"]["MultiplePreviewRequest"]
          | components["schemas"]["SinglePreviewRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  swatch_api_templates__name__swatch_get: {
    parameters: {
      query: {
        colour: string;
      };
      header?: never;
      path: {
        name: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SwatchResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  thumbnail_api_templates__name__thumbnail_get: {
    parameters: {
      query?: {
        colour?: string | null;
      };
      header?: never;
      path: {
        name: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_workspace_api_workspace_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["WorkspaceSummary"];
        };
      };
    };
  };
  spa_fallback__full_path__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        full_path: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
}
