"""``garment-profiles/{name}.yaml``: the garment definition. Generated by
``new``, PRD 8a.

Nothing commercial lives here -- only which blueprint, which printer, and print
geometry. Reused by every listing built on the same garment.
"""

from __future__ import annotations

from pathlib import Path
from typing import Literal

import yaml
from pydantic import BaseModel, ConfigDict, ValidationError, field_validator

from etsy_listings.config.errors import ConfigLoadError, format_validation_error


class PrintArea(BaseModel):
    model_config = ConfigDict(extra="forbid")

    width: int
    height: int


class BlueprintRef(BaseModel):
    """Which blank this garment is, as a human orders one (PRD 23).

    ``brand`` and ``model`` identify it; ``title`` is readable context and
    takes no part in matching. Printify's titles are generic ("Unisex
    Garment-Dyed T-shirt" is sold by several brands) and are rewritten over
    time, so one is not an identifier -- a garment profile naming only a title
    could never resolve, which is what the e2e layer caught.
    """

    model_config = ConfigDict(extra="forbid", frozen=True)

    brand: str
    model: str
    title: str = ""
    """Optional, and refreshed by ``new``. A garment profile identifying a
    garment only by part number is hard to read; a drifted one is stale
    prose, not a broken profile."""

    def __str__(self) -> str:
        """How the pair is quoted in an error or a log line: "Comfort Colors 1717"."""
        return f"{self.brand} {self.model}".strip()


class GarmentProfile(BaseModel):
    model_config = ConfigDict(extra="forbid")

    blueprint: BlueprintRef
    print_provider: str
    placeholder: str
    print_area: PrintArea
    sizes: list[str]
    colors: dict[str, Literal["light", "dark"]] = {}
    """Human-classified once via ``new``, not auto-seeded -- Printify's
    catalog carries no hex colour value in this codebase. Drives artwork
    (light/dark ink) resolution for listings with more than one design file."""

    preview_template: str | None = None
    """A ``colour-matrix`` template the editor uses to judge colours.

    Not a ``media:`` default -- listing mockups still live in
    ``listing.media``, and a listing that never names this template still
    renders whatever ``media:`` does (A13, PRD 29). Optional so garment
    profiles written before the field existed still load. ``new`` does not
    prompt; it is hand-edited the same way ``colors:`` is classified.
    """

    @field_validator("preview_template", mode="before")
    @classmethod
    def _blank_preview_template_is_unset(cls, value: object) -> object:
        """``preview_template:`` with nothing after it, or a blank string,
        names no template -- the same as omitting the field."""
        if value == "":
            return None
        return value

    @classmethod
    def load(cls, path: Path) -> GarmentProfile:
        if not path.is_file():
            raise ConfigLoadError(path, "garment profile file not found")
        raw = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
        try:
            return cls.model_validate(raw)
        except ValidationError as exc:
            raise format_validation_error(path, exc) from exc
