"""``profiles/{name}.yaml``: the garment definition. Generated by ``new``, PRD 8a.

Nothing commercial lives here -- only which blueprint, which printer, and print
geometry. Reused by every listing built on the same garment.
"""

from __future__ import annotations

from pathlib import Path
from typing import Literal

import yaml
from pydantic import BaseModel, ConfigDict, ValidationError

from etsy_listings.config.errors import ConfigLoadError, format_validation_error


class PrintArea(BaseModel):
    model_config = ConfigDict(extra="forbid")

    width: int
    height: int


class Profile(BaseModel):
    model_config = ConfigDict(extra="forbid")

    blueprint: str
    print_provider: str
    placeholder: str
    print_area: PrintArea
    sizes: list[str]
    colour_tone: dict[str, Literal["light", "dark"]] = {}
    """Human-classified once via ``new``, not auto-seeded -- Printify's
    catalog carries no hex colour value in this codebase. Drives artwork
    (light/dark ink) resolution for listings with more than one design file."""

    @classmethod
    def load(cls, path: Path) -> Profile:
        if not path.is_file():
            raise ConfigLoadError(path, "profile file not found")
        raw = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
        try:
            return cls.model_validate(raw)
        except ValidationError as exc:
            raise format_validation_error(path, exc) from exc
