"""``profiles/{name}.yaml``: the garment definition. Generated by ``new``, PRD 8a.

Nothing commercial lives here -- only which blueprint, which printer, and print
geometry. Reused by every listing built on the same garment.
"""

from __future__ import annotations

from pathlib import Path
from typing import Literal

import yaml
from pydantic import BaseModel, ConfigDict, ValidationError

from etsy_listings.config.errors import ConfigLoadError, format_validation_error


class PrintArea(BaseModel):
    model_config = ConfigDict(extra="forbid")

    width: int
    height: int


class BlueprintRef(BaseModel):
    """Which blank this garment is, as a human orders one (PRD 23).

    ``brand`` and ``model`` identify it; ``title`` is readable context and
    takes no part in matching. Printify's titles are generic ("Unisex
    Garment-Dyed T-shirt" is sold by several brands) and are rewritten over
    time, so one is not an identifier -- a profile naming only a title could
    never resolve, which is what the e2e layer caught.
    """

    model_config = ConfigDict(extra="forbid", frozen=True)

    brand: str
    model: str
    title: str = ""
    """Optional, and refreshed by ``new``. A profile identifying a garment
    only by part number is hard to read; a drifted one is stale prose, not a
    broken profile."""

    def __str__(self) -> str:
        """How the pair is quoted in an error or a log line: "Comfort Colors 1717"."""
        return f"{self.brand} {self.model}".strip()


class Profile(BaseModel):
    model_config = ConfigDict(extra="forbid")

    blueprint: BlueprintRef
    print_provider: str
    placeholder: str
    print_area: PrintArea
    sizes: list[str]
    colour_tone: dict[str, Literal["light", "dark"]] = {}
    """Human-classified once via ``new``, not auto-seeded -- Printify's
    catalog carries no hex colour value in this codebase. Drives artwork
    (light/dark ink) resolution for listings with more than one design file."""

    @classmethod
    def load(cls, path: Path) -> Profile:
        if not path.is_file():
            raise ConfigLoadError(path, "profile file not found")
        raw = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
        try:
            return cls.model_validate(raw)
        except ValidationError as exc:
            raise format_validation_error(path, exc) from exc
